# Generated by Django 5.1.2 on 2024-10-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisan', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name_product', models.CharField(max_length=50)),
                ('description_product', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product/images')),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisan.artisanmodel')),
                ('groups', models.ManyToManyField(blank=True, related_name='product_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='product_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
